# Dockerfile-backend
FROM node:14
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

RUN rm -rf ./build/dnd.db
COPY ./src/dnd.db ./build/dnd.db

EXPOSE 80
CMD [ "node", "build/index.js" ]